"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Pelicula_1 = require("./Pelicula");
var Cliente_1 = require("./Cliente");
var sala_1 = require("./sala");
var Compra_1 = require("./Compra");
var Asiento_1 = require("./Asiento");
var Aperitivos_1 = require("./Aperitivos");
var Accesorio_1 = require("./Accesorio");
var Comestible_1 = require("./Comestible");
var asiento1 = new Asiento_1.Asiento(1, "A");
var aperitivo1 = new Aperitivos_1.Aperitivos("Chocolate");
var aperitivo2 = new Aperitivos_1.Aperitivos("Galleta");
var accesorio1 = new Accesorio_1.Accesorio("Cangilera temática");
var accesorio2 = new Accesorio_1.Accesorio("Poster de la película");
var comestible1 = new Comestible_1.Comestible("Palomitas", 1.5);
var comestible2 = new Comestible_1.Comestible("CocaCola", 1.0);
var sala1 = new sala_1.Sala("Sala 1");
sala1.AsignarAperitivo(aperitivo1);
sala1.AsignarAperitivo(aperitivo2);
sala1.AsignarAccesorio(accesorio1);
sala1.AsignarAccesorio(accesorio2);
var pelicula1 = new Pelicula_1.Pelicula("Avatar", "Ciencia Ficción", "James Cameron", "insert descripcion(no se)", 180, sala1);
sala1.AsignarAsiento(asiento1);
var cliente1 = new Cliente_1.Cliente("Juan");
cliente1.asiento.push(asiento1);
cliente1.comestibles.push(comestible1, comestible2);
var compra1 = new Compra_1.Compra(cliente1, pelicula1, sala1, "12/05/2025");
compra1.imprimirResumenCompra();
// Crear nueva compra 
var aperitivo3 = new Aperitivos_1.Aperitivos("Papas");
var aperitivo4 = new Aperitivos_1.Aperitivos("Jugo");
var accesorio3 = new Accesorio_1.Accesorio("Sable láser miniatura");
var accesorio4 = new Accesorio_1.Accesorio("Póster edición limitada");
var sala2 = new sala_1.Sala("Sala 2");
sala2.AsignarAperitivo(aperitivo3);
sala2.AsignarAperitivo(aperitivo4);
sala2.AsignarAccesorio(accesorio3);
sala2.AsignarAccesorio(accesorio4);
var pelicula2 = new Pelicula_1.Pelicula("Star Wars: Episodio III - La venganza de los Sith", "Ciencia Ficción / Aventura", "George Lucas", "Anakin Skywalker se convierte en Darth Vader en medio del colapso de la República.", 140, sala2);
var asiento5 = new Asiento_1.Asiento(5, "D");
sala2.AsignarAsiento(asiento5);
var cliente2 = new Cliente_1.Cliente("Laura");
cliente2.asiento.push(asiento5);
var comestible5 = new Comestible_1.Comestible("HotDog", 2.0);
var comestible6 = new Comestible_1.Comestible("Botella de Agua", 1.5);
cliente2.comestibles.push(comestible5, comestible6);
var compra2 = new Compra_1.Compra(cliente2, pelicula2, sala2, "13/05/2025");
compra2.imprimirResumenCompra();
