"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Pelicula_1 = require("./Pelicula");
var Cliente_1 = require("./Cliente");
var sala_1 = require("./sala");
var Compra_1 = require("./Compra");
var Asiento_1 = require("./Asiento");
var Aperitivos_1 = require("./Aperitivos");
var Accesorio_1 = require("./Accesorio");
var Comestible_1 = require("./Comestible");
var asiento1 = new Asiento_1.Asiento(1, "A");
var asiento2 = new Asiento_1.Asiento(2, "G");
var asiento3 = new Asiento_1.Asiento(3, "B");
var aperitivo1 = new Aperitivos_1.Aperitivos("Palomitas");
var aperitivo2 = new Aperitivos_1.Aperitivos("Refresco");
var accesorio1 = new Accesorio_1.Accesorio("Cangilera tematica");
var accesorio2 = new Accesorio_1.Accesorio("Poster de la pelicula");
var comestible1 = new Comestible_1.Comestible("Chocolatina", 1.5);
var comestible2 = new Comestible_1.Comestible("Galletas", 1.0);
var sala1 = new sala_1.Sala("Sala 1", 10);
var pelicula1 = new Pelicula_1.Pelicula("Avatar", "Ciencia Ficción", "James Cameron", "insert descripcion(no se)", 180, sala1);
pelicula1.AsignarSala(sala1);
var disponibles = pelicula1.sala.AsignarAsiento(asiento1);
var cliente1 = new Cliente_1.Cliente("Juan");
var compra1 = new Compra_1.Compra(cliente1, pelicula1, sala1, "12/05/2025");
console.log(compra1.obtenerDetallesCompra());
